version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8290:8290"
      - "8300:8300"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14.3
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
