server:
  port: 8290

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

management:
  server:
    port: 8299
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus