server:
  port: 8290

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

management:
  server:
    port: 8300
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

spring:
  security:
    oauth2:
      client:
        provider:
          hardship:
            token-uri: ${HARDSHIP_API_OAUTH_URL}
          ccc:
            token-uri: ${CCC_API_OAUTH_URL}
        registration:
          hardship:
            client-id: ${HARDSHIP_API_OAUTH_CLIENT_ID}
            client-secret: ${HARDSHIP_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
      resource-server:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}

services:
  hardship-api:
    base-url: ${HARDSHIP_API_BASE_URL}
    hardship-endpoints:
      find-url: ${services.hardship-api.base-url}/api/internal/v1/hardship/{hardshipReviewId}
      create-url: ${services.hardship-api.base-url}/api/internal/v1/hardship/
      update-url: ${services.hardship-api.base-url}/api/internal/v1/hardship/
      rollback-url: ${services.hardship-api.base-url}/api/internal/v1/hardship/rollback
  contribution-api:
    base-url: ${CONTRIBUTION_API_BASE_URL}
    contribution-endpoints:
      calculate-contribution-url: ${services.contribution-api.base-url}/api/internal/v1/contribution/calculate-contribution
      request-transfer-url: ${services.contribution-api.base-url}/api/internal/v1/contribution/request-transfer

retry-config:
  max-retries: 3
  min-back-off-period: 5
  jitter-value: 0.75

springdoc:
  packagesToScan: uk.gov.justice.laa.maat.orchestration
  api-docs:
    path: open-api/api-docs

  swagger-ui:
    path: open-api/swagger-ui.html
    operationsSorter: method

sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SENTRY_ENV}
  release: 0.0.1
  servername: aws-eks-container
  send-default-pii: true
  attach-stacktrace: true
  sample-rate: ${SENTRY_SAMPLE_RATE}
