server:
  port: 8290

logging:
  level:
    root: ${LOG_LEVEL}
    org.springframework.web: ${LOG_LEVEL}
    org.springframework.security: ${LOG_LEVEL}

management:
  server:
    port: 8300
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    propagation:
      type: w3c,b3

spring:
  security:
    oauth2:
      client:
        provider:
          hardship:
            token-uri: ${HARDSHIP_API_OAUTH_URL}
          ccc:
            token-uri: ${CCC_API_OAUTH_URL}
          ccp:
            token-uri: ${CCP_API_OAUTH_URL}
          cma:
            token-uri: ${CMA_API_OAUTH_URL}
          validation:
            token-uri: ${VALIDATION_API_OAUTH_URL}
          maat-api:
            token-uri: ${MAAT_API_OAUTH_URL}
          cat:
            token-uri: ${CAT_API_OAUTH_URL}
          evidence:
            token-uri: ${EVIDENCE_API_OAUTH_URL}
        registration:
          hardship:
            client-id: ${HARDSHIP_API_OAUTH_CLIENT_ID}
            client-secret: ${HARDSHIP_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
          ccc:
            client-id: ${CCC_API_OAUTH_CLIENT_ID}
            client-secret: ${CCC_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
          ccp:
            client-id: ${CCP_API_OAUTH_CLIENT_ID}
            client-secret: ${CCP_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
          cma:
            client-id: ${CMA_API_OAUTH_CLIENT_ID}
            client-secret: ${CMA_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
          validation:
            client-id: ${VALIDATION_API_OAUTH_CLIENT_ID}
            client-secret: ${VALIDATION_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
          maat-api:
            client-id: ${MAAT_API_OAUTH_CLIENT_ID}
            client-secret: ${MAAT_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
          cat:
            client-id: ${CAT_API_OAUTH_CLIENT_ID}
            client-secret: ${CAT_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
          evidence:
            client-id: ${EVIDENCE_API_OAUTH_CLIENT_ID}
            client-secret: ${EVIDENCE_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
      resource-server:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}

services:
  hardship-api:
    base-url: ${HARDSHIP_API_BASE_URL}
    registrationId: hardship

  contribution-api:
    base-url: ${CCC_API_BASE_URL}
    registrationId: ccc

  crown-court-api:
    base-url: ${CCP_API_BASE_URL}
    registrationId: ccp

  cma-api:
    base-url: ${CMA_API_BASE_URL}
    registrationId: cma

  maat-api:
    base-url: ${MAAT_API_BASE_URL}
    registrationId: maat-api

  cat-api:
    base-url: ${CAT_API_BASE_URL}
    registrationId: cat

  evidence-api:
    base-url: ${EVIDENCE_API_BASE_URL}
    registrationId: evidence

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retry-exceptions:
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadGateway
          - org.springframework.web.reactive.function.client.WebClientResponseException.TooManyRequests
          - org.springframework.web.reactive.function.client.WebClientResponseException.ServiceUnavailable
          - org.springframework.web.reactive.function.client.WebClientResponseException.GatewayTimeout
        
springdoc:
  packagesToScan: uk.gov.justice.laa.maat.orchestration
  api-docs:
    path: open-api/api-docs

  swagger-ui:
    path: open-api/swagger-ui.html
    operationsSorter: method

sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SENTRY_ENV}
  release: 0.0.1
  servername: aws-eks-container
  send-default-pii: true
  attach-stacktrace: true
  sample-rate: ${SENTRY_SAMPLE_RATE}
