server:
  port: 8290

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

management:
  server:
    port: 8300
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

spring:
  security:
    oauth2:
      client:
        provider:
          hardship:
            token-uri: ${HARDSHIP_API_OAUTH_URL}
          ccc:
            token-uri: ${CCC_API_OAUTH_URL}
          ccp:
            token-uri: ${CCP_API_OAUTH_URL}
          cma:
            token-uri: ${CMA_API_OAUTH_URL}
          validation:
            token-uri: ${VALIDATION_API_OAUTH_URL}
          maat-api:
            token-uri: ${MAAT_API_OAUTH_URL}
        registration:
          hardship:
            client-id: ${HARDSHIP_API_OAUTH_CLIENT_ID}
            client-secret: ${HARDSHIP_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
          ccc:
            client-id: ${CCC_API_OAUTH_CLIENT_ID}
            client-secret: ${CCC_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
          ccp:
            client-id: ${CCP_API_OAUTH_CLIENT_ID}
            client-secret: ${CCP_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
          cma:
            client-id: ${CMA_API_OAUTH_CLIENT_ID}
            client-secret: ${CMA_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
          validation:
            client-id: ${VALIDATION_API_OAUTH_CLIENT_ID}
            client-secret: ${VALIDATION_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
          maat-api:
            client-id: ${MAAT_API_OAUTH_CLIENT_ID}
            client-secret: ${MAAT_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
      resource-server:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}

services:
  hardship-api:
    base-url: ${HARDSHIP_API_BASE_URL}
    endpoints:
      find-url: ${services.hardship-api.base-url}/api/internal/v1/hardship/{hardshipReviewId}
      create-url: ${services.hardship-api.base-url}/api/internal/v1/hardship
      update-url: ${services.hardship-api.base-url}/api/internal/v1/hardship
      rollback-url: ${services.hardship-api.base-url}/api/internal/v1/hardship/rollback

  contribution-api:
    base-url: ${CCC_API_BASE_URL}
    endpoints:
      request-transfer-url: ${services.contribution-api.base-url}/api/internal/v1/contribution/request-transfer
      calculate-contribution-url: ${services.contribution-api.base-url}/api/internal/v1/contribution/calculate-contribution
      check-contribution-rule-url: ${services.contribution-api.base-url}/api/internal/v1/contribution/check-contribution-rule
      contribution-summaries-url: ${services.contribution-api.base-url}/api/internal/v1/contribution/summaries

  crown-court-api:
    base-url: ${CCP_API_BASE_URL}
    endpoints:
      update-application-url: ${services.crown-court-api.base-url}/api/internal/v1/proceedings
      update-crown-court-url: ${services.crown-court-api.base-url}/api/internal/v1/proceedings/update-crown-court

  cma-api:
    base-url: ${CMA_API_BASE_URL}
    endpoints:
      find-url: ${services.cma-api.base-url}/api/internal/v1/assessment/means/{financialAssessmentId}/applicantId/{applicantId}
      create-url: ${services.cma-api.base-url}/api/internal/v1/assessment/means
      update-url: ${services.cma-api.base-url}/api/internal/v1/assessment/means

  maat-api:
    base-url: ${MAAT_API_BASE_URL}
    endpoints:
      call-stored-proc-url: ${services.maat-api.base-url}/api/internal/v1/assessment/execute-stored-procedure

retry-config:
  max-retries: 3
  min-back-off-period: 5
  jitter-value: 0.75

springdoc:
  packagesToScan: uk.gov.justice.laa.maat.orchestration
  api-docs:
    path: open-api/api-docs

  swagger-ui:
    path: open-api/swagger-ui.html
    operationsSorter: method

sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SENTRY_ENV}
  release: 0.0.1
  servername: aws-eks-container
  send-default-pii: true
  attach-stacktrace: true
  sample-rate: ${SENTRY_SAMPLE_RATE}
