server:
  port: 8290

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

management:
  server:
    port: 8300
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

services:
  hardship-api:
    base-url: ${HARDSHIP_API_BASE_URL}
    hardship-endpoints:
      find-url: ${services.hardship-api.base-url}/api/internal/v1/hardship/hardshipReviewId
      calculate-hardship-for-detail-url: ${services.hardship-api.base-url}/api/internal/v1/hardship/calculate-hardship-for-detail
      create-url: ${services.hardship-api.base-url}/api/internal/v1/hardship/
      update-url: ${services.hardship-api.base-url}/api/internal/v1/hardship/
      rollbacl-url: ${services.hardship-api.base-url}/api/internal/v1/hardship/rollback
  contribution-api:
    base-url: ${CONTRIBUTION_API_BASE_URL}
    contribution-endpoints:
      calculate-contribution-url: ${services.contribution-api.base-url}/api/internal/v1/contribution/calculate-contribution
      request-transfer-url: ${services.contribution-api.base-url}/api/internal/v1/contribution/request-transfer

retry-config:
  max-retries: 3
  min-back-off-period: 5
  jitter-value: 0.75