# Default values for laa-maat-orchestration.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-crime-apps-team/laa-maat-orchestration-dev
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: latest

sentry:
  sampleRate: 1.0

aws_region: eu-west-2

java:
  host_env: production

jwt:
  issuerUri: https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_ZaFnb3kFD

maatApi:
  baseUrl: https://maat-cd-api.legalservices.gov.uk
  oauthUrl: https://maat-cd-api-prd.auth.eu-west-2.amazoncognito.com/oauth2/token

hardshipApi:
  baseUrl: http://laa-crime-hardship.laa-crime-hardship-prod.svc.cluster.local
  oauthUrl: https://laa-crime-auth-hardship.auth.eu-west-2.amazoncognito.com/oauth2/token

cccApi:
  baseUrl: http://laa-crown-court-contribution.laa-crown-court-contribution-prod.svc.cluster.local
  oauthUrl: https://laa-crime-auth-ccc.auth.eu-west-2.amazoncognito.com/oauth2/token

ccpApi:
  baseUrl: http://laa-crown-court-proceeding.laa-crown-court-proceeding-prod.svc.cluster.local
  oauthUrl: https://laa-crime-auth-ccp.auth.eu-west-2.amazoncognito.com/oauth2/token

cmaApi:
  baseUrl: http://laa-crime-means-assessment.laa-crime-means-assessment-prod.svc.cluster.local
  oauthUrl: https://laa-crime-auth-cma.auth.eu-west-2.amazoncognito.com/oauth2/token

validationApi:
  baseUrl: https://laa-crime-validation-prod.apps.live.cloud-platform.service.justice.gov.uk
  oauthUrl: https://laa-crime-auth-validation.auth.eu-west-2.amazoncognito.com/oauth2/token

catApi:
  baseUrl: http://laa-crime-application-tracking-service.laa-crime-application-tracking-service-prod.svc.cluster.local
  oauthUrl: https://laa-crime-auth-ats.auth.eu-west-2.amazoncognito.com/oauth2/token

evidenceApi:
  baseUrl: http://laa-crime-evidence.laa-crime-evidence-prod.svc.cluster.local
  oauthUrl: https://laa-crime-auth-evidence.auth.eu-west-2.amazoncognito.com/oauth2/token

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}


service:
  type: ClusterIP
  port: 8290

ingress:
  environmentName: laa-maat-orchestration-prod
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    external-dns.alpha.kubernetes.io/set-identifier: "laa-maat-orchestration-laa-maat-orchestration-prod-green"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "300"
  externalAnnotations: {}
  internalHost:
    host: laa-maat-orchestration-prod.apps.live.cloud-platform.service.justice.gov.uk
    path: /api/internal/v1/orchestration
  externalHost:
    host: laa-maat-orchestration-prod.apps.live.cloud-platform.service.justice.gov.uk
    paths:
      swaggerPath: /open-api/swagger-ui
      openApiPath: /open-api/api-docs
  tls: []
  className: default

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

actuator:
  metrics:
    enabled: true
    scrapeInterval: 15s
    path: /actuator/prometheus
  health:
    path: /actuator/health
  port: 8300
  liveness:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 5
  readiness:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 5

logging:
  level: INFO
