name: Commit Checks

on:
  push:
    branches-ignore: [main]

jobs:
  run-commit-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Commit message check
        env:
          CMTS: ${{ github.event.commits }}
        run: |
          echo "SHA: ${{ github.event.ref }}"
          
          commits=${{ github.event.commits }}
          
          echo "${commits[*]}"
          
          echo "Total commits: ${#commits[@]}"
          
          actual_commits=${commits[0]}

          exit 0
