name: Commit Checks

on:
  push:
    branches-ignore: [main]

jobs:
  run-commit-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Commit message check
        run: |
          echo "SHA: ${{ github.event.ref }}"
          
          messages="${{ join(github.event.commits.*.message, ',') }}"
          echo $messages
          
          needs_rebase=${{ contains(github.event.commits.*.message, 'forgot') }}
          echo $needs_rebase
          
          if $needs_rebase; then
            echo "Please fix-up your PR to make commits more meaningful."
            exit 1
          fi
          
          exit 0
