name: Commit Checks

on:
  push:
    branches-ignore: [main]

jobs:
  run-commit-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Commit message check
        env:
          SHA: ${{ github.event.push.ref }}
          GC: ${{ toJson(github.event) }}
        run: |
          echo "$GC"
          
          echo "SHA: $SHA"
          
          commits=${{ github.event.push.commits }}
          
          for commit in "${commits[@]}"
          do
            echo "Commit msg $commit"
          done

          exit 0
