name: Commit Checks

on:
  push:
    branches-ignore: [main]

jobs:
  run-commit-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Commit message check
        run: |
          echo "SHA: ${{ github.event.ref }}"
          
          commits=${{ github.event.commits }}
          
          echo "${commits[*]}"
          
          for key in "${!commits[@]}"
          do
            echo "Key: $key"
            echo "Value: ${commits[$key]}"
          done
          
          echo "Total commits: ${#commits[@]}"
          
          actual_commits=${commits[0]}
          
          echo "${actual_commits[*]}"

          exit 0
