name: Commit Checks

on:
  push:
    branches-ignore: [main]

jobs:
  run-commit-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Commit message check
        run: |
          echo "SHA: ${{ github.event.ref }}"
          echo "Modified: ${{ github.event.head_commit.timestamp }}"
          
          messages="${{ join(github.event.push.commits.*.message, ',') }}"
          echo $messages
          
          needs_rebase=${{ contains(github.event.push.commits.*.message, 'forgot') }}
          echo "Needs rebase: ${needs_rebase}"
          
          if [[ $messages == *"forgot"* ]]; then
            echo "Please fix-up your PR to make commits more meaningful."
            exit 1
          fi
          
          exit 0
