name: Commit Checks

on:
  push:
    branches-ignore: [main]

jobs:
  run-commit-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Commit message check
        run: |
          sha=${{ github.event.push.base_ref }}
          
          echo "SHA: $sha"
          
          commits=${{ github.event.push.commits }}
          
          for commit in "${commits[@]}"
          do
            echo "Commit msg $commit"
          done

          exit 0
