name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  run-pr-checks:
    runs-on: ubuntu-latest
    steps:
      - name: PR description check
        env:
          TITLE: ${{ github.event.pull_request.title }}
          DESCRIPTION: ${{ github.event.pull_request.body }}
        run: |
          echo $TITLE
          echo $DESCRIPTION
          
          if [[ $DESCRIPTION == *"Describe what you did and why"* ]]; then
            echo "Please add a meaningful description to your PR."
            exit 1
          fi
          
          exit 0
      - name: Jira link check
        env:
          DESCRIPTION: ${{ github.event.pull_request.body }}
        run: |
          echo $DESCRIPTION

          if [[ $DESCRIPTION == *"https://dsdmoj.atlassian.net/browse/LCAM-XXX"* ]]; then
            echo "Please update the Jira link to point to the correct work item."
            exit 1
          fi

          exit 0
