name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - name: PR description check
        env:
          TITLE: {{ github.event.pull_request.title }}
#          DESCRIPTION: {{ github.event.pull_request.description }}
        run: |
          echo $TITLE
#          echo $DESCRIPTION
          
          exit 0
